---
title: Pogo Tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
email: ouroffice19@gmail.com
description: This demo store is a Jekyll-built static site. The shopping cart runs
  on Snipcart—it lets you add custom e-commerce to any site in minutes.
baseurl: 
url: 
twitter_username: Zoolemon
github_username: Zoolemon
plugins:
- jekyll-feed
